### ISSUE TITLE
Swapping the bmon and rgmon folders does not work

### ISSUE THREAD

**Issue by DJLoogie** [jojobear13/shinpokered#1]
So I was gonna try and play this hack using the rgmon folders sprites so I simply renamed them both and it actually causes this unique error that I have taken a screen shot of.. I can only get this error with this hack weirdly, is there any solution to this so I can play this hack with the rg sprites instead of the blue sprites?
![~_shinpokered-master 11_25_2019 1_20_51 PM](https://user-images.githubusercontent.com/55605193/69660028-7209ea00-104d-11ea-8e4c-ab7bab5a3840.png)

**Comment by jojobear13** [comment]
The red/green sprites take up slightly more space than the red/blue sprites, so you are running out of space in the rom bank. All the back and front sprites are included across five different sections (PICS_1 through PICS_5) in main.asm and each are assigned a different rom bank. You can see here that PICS_4 is in rom bank $C.
![image](https://user-images.githubusercontent.com/47074297/69909963-00bd9480-13c9-11ea-8744-efad67572434.png)

You will have to move these two lines into another PICS_ section since they cause PICS_4 to be too big to fit in a single rom bank (limited to 4000 bytes). Moving them to PICS_5 works.
![image](https://user-images.githubusercontent.com/47074297/69910072-df5da800-13ca-11ea-9355-f4df2372180a.png)

Then you will need to assign each PICS_ section a new rom bank and update the information in the pokered.link file. Rom banks $2D and up are good candidates

**Comment by jojobear13** [comment]
Quick update: V1.08 has a folder with instructions on using the rgmon and ymon sprites. Just swap in the new main.asm and pokered.link to get compiling working.
