### ISSUE TITLE
Buggy Guard Positioning in front of Silph Co.

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#145]
There was an instance that the guard in front of Silph Co. appeared one tile below his updated position (1 tile to the right and 1 tile below Silph Co.'s front door). When the player reached that tile the guard appeared normally in his correct second position (1 tile to the right of the front door to Silph Co.). This only happened once. Upon loading a previous the issue didn't appear again. 

Update: He also spins around. I am not sure if he was supposed to do that in the original version, seems unrealistic since he is supposed to be asleep.

**Comment by wisp92** [comment]
I kept the save file in case you need it. Just pm me.

**Comment by jojobear13** [comment]
attach the sav file and I'll take a look

**Comment by wisp92** [comment]
[Pokemon - Red Version (UE)[Shin].zip](https://github.com/jojobear13/shinpokered/files/6951394/Pokemon.-.Red.Version.UE.Shin.zip)

**Comment by wisp92** [comment]
Interesting I didn't know I can attach files in Girhub comments. Hope it helps.

**Comment by jojobear13** [comment]
Helps alot!

The cause of this was really tricky to track down, but it looks like this is a Gamefreak bug. This NPC is supposed to be facing down, but he looks around even in the original game. I pulled up a random LP on youtube to check (https://youtu.be/iPE-WtW8C-Q?t=410). The UpdateNPCSprite function seems to not do certain updates for the 15th object on the map, and it turns out this particular rocket grunt is in fact the 15th object on the Saffron City map. In fact, I think Saffron is the only map in the game which hits the 15 object limit. This NPC was actually omitted in Yellow version since the following Pikachu occupies an object slot.

I'll look into fixing the oversight.

**Comment by wisp92** [comment]
Glad I could help. I found out some other minor bugs in the general game but I'll post them as a single issue as soon as I have checked the whole areas.

**Comment by jojobear13** [comment]
> Glad I could help. I found out some other minor bugs in the general game but I'll post them as a single issue as soon as I have checked the whole areas.

Cool. I’ll delay the next version release until you post it and I can work on it some more.

**Comment by epman100** [comment]
this was definitely a bug in the original Pokemon Red/Blue gen 1 games as it does sometimes happen as I have seen it myself
