### ISSUE TITLE
Japanese Blue option

### ISSUE THREAD

**Issue by GLSWV** [jojobear13/shinpokered#195]
Is it possible to add the option to build japanese Blue? I believe the only differences from western Blue are the wild Pokémon encounter tables, Game Corner prizes, and in-game trades (restoring the original "went and evolved" dialogue).

**Comment by jojobear13** [comment]
Its possible. Just kind of tedious.

**Comment by jojobear13** [comment]
Note to self: 
-add blueJP and redJP. 
-use fire red 'dex entries as a basis for redJP and green 'dex entries

**Comment by GLSWV** [comment]
Another cool option from the japanese versions (and the european versions) that would be nice to have, although no less tedious to implement, is displaying the height and weight in metric units.

I'm not sure how the english version implemented the imperial system, but if it's a conversion then maybe it can be disabled.

**Comment by jojobear13** [comment]
> Another cool option from the japanese versions (and the european versions) that would be nice to have, although no less tedious to implement, is displaying the height and weight in metric units.
> 
> I'm not sure how the english version implemented the imperial system, but if it's a conversion then maybe it can be disabled.

The US releases don't do any conversion. The data and text formatting was redone to use imperial units during localization.
The US releases expresses height and weight in units of feet, inches, and 1/10th pounds. But The japanese games express those in units of just kilograms and meters. 

However, this may be easier than the pokedex entries. I can re-use the existing formatting by converting the height into meters up to two decimal places. A decimal symbol replaces the feet symbol, and "m" replaces the inches symbol. Pounds can be directly converted into kilograms. Rather than do this in-game, I 'll make an Excel spreadsheet to parse out the data, convert it, then re-organize the data back into something that's easy to copy-paste.

**Comment by jojobear13** [comment]
Conversions are all done. That was easier than I thought it would be.

[converted entries.zip](https://github.com/jojobear13/shinpokered/files/7652375/converted.entries.zip)

**Comment by jojobear13** [comment]
Oh, that was easier than I though it would be.

[converted entries.zip](https://github.com/jojobear13/shinpokered/files/7652437/converted.entries.zip)

**Comment by GLSWV** [comment]
I've fixed the metric values to match the official ones. The slight differences could have resulted from the original conversion to imperial by GF.
[converted entries_fix.zip](https://github.com/jojobear13/shinpokered/files/7653756/converted.entries_fix.zip)

**Comment by jojobear13** [comment]
Yeah, that's very likely what happened. Thanks for the updated values.
