### ISSUE TITLE
Optimize XP division

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#23]
I am reluctant to open this as an issue but I noticed the when Exp.Share is used the total amount of XP is reduced. For example, a total of 588XP, when one PKMN participated in the battle and the part has a total of 6 is split in 291 + 6 * 45 = 561, while in the same scenario with part of 5 not fainted PKMN, results in 291 + 5 * 57 = 576.

Clearly, there is some rounding error here, but since the XP is calculated based on dividing the opponent's stats I wonder if it's possible to optimize it?

**Comment by jojobear13** [comment]
It's a rounding error due to shifting bytes around. Gamefreak did a lot of doubling and halving in the engine by just shifting left or right by one bit. Saves memory and it's fast. I'm not going to mess around with this because EXP All takes a long time to run even on a retail cart. You just never noticed it because Gamefreak put in all the textbox spam about each party member getting exp. The real reason it was there? To hide the obvious lag.

This got alleviated with Gen 2 since the GBC has a nice speedy mode that can be accessed. But even then, the now-a-hold-item exp share was a rare item for a reason.
