### ISSUE TITLE
(Rework limits on transform) Transformed ditto sometimes uses struggle

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#246]
[No idea what causes it, goodluck tho.](https://www.youtube.com/watch?v=2yS0z_cxbH0)

I transformed into the transformed ditto after. All I have to say is...nice.

![image](https://user-images.githubusercontent.com/63818362/212066394-e3541d40-14a4-4a45-8e16-2c2706e63ff3.png)
![image](https://user-images.githubusercontent.com/63818362/212066836-b654091f-6b20-4e43-adf2-8b83fe812a9a.png)

**Comment by jojobear13** [comment]
Note to self - possibly the same source issue as #244

**Comment by jojobear13** [comment]
I know what's going on here.

Genger has:
- confuse ray
- thunderbolt
- seismic toss
- mimic

Gengar uses mimic and copies transform.

Genger has:
- confuse ray
- thunderbolt
- seismic toss
- transform

Ditto uses transform. Here is where things get interesting. You may have heard about how gen 1 can get stuck in an endless loop if it's a ditto vs. a ditto because only transform can be used and the PP gets reset to 5 each time. A long time ago, I tried to avoid this situation by editing transform's effect to detect when it copies the opponent's  transform move and change it to struggle. That way two dittos will would struggle-out against each other.

So after Ditto transforms, it's moves are:
- confuse ray
- thunderbolt
- seismic toss
- struggle

And Gengar can transform once more to make its moves:
- confuse ray
- thunderbolt
- seismic toss
- struggle

This should be revisited since enemy pokemon now obey PP limitations. It would be better to copy the transform move but set its PP to zero.

**Comment by DiabloStorm** [comment]
> It would be better to copy the transform move but set its PP to zero.

Depends... for AI only or player also? If you fatfinger transform twice (doing it purposefully in this scenario only cuts the pp of all your moves, so most wouldn't...) if then you're greeted with 0 pp for transform after that mistake and wish to transform into a different, non-ditto pokemon, you now can't because a developer has made the pp zero.

**Comment by jojobear13** [comment]
Transform's effect is coded to apply to both player and opponent equally. 

Unfortunately, I'm having trouble seeing a way out. Stadium's solution was to hard-code it so that transform straight up fails if used against a ditto or if a ditto uses it against a 'mon that has transform (looks like they forgot about mew). Gen 2 was where it can't be used against a 'mon in a transformed state. The main problem is that transform perpetuates itself by refreshing move PP. There needs to be something that makes transform have a finite amount of PP in any one battle.

Here's another idea. Transform will detect when it copies the opponent's transform move. If the opponent has between [0, 5] PP for the move remaining, then it will copy that PP amount instead of loading a constant 5. That way the transform PP between player and opponent will gradually decrease in a transformation loop and end in a struggle battle.

**Comment by jojobear13** [comment]
Implemented in 8a6ff7eaef32e990217de6328acee76e847c9e60

Transform will copy the opponent's Transform move. If the PP for it on the opponent is 5 or less, that PP value is copied as well and deducted by 1 (or a deduction of 2 if the opponent goes first and also uses Transform). Transform paradox loops now have a definite end state, and either player can continue to re-Transform for several turns in case switching or a KO occurs.
