### ISSUE TITLE
Request: Dragonite should learn Fly

### ISSUE THREAD

**Issue by rjd1922** [jojobear13/shinpokered#247]
Charizard and Dragonite should be able to learn Fly by HM. It makes sense and Charizard could learn Fly starting in Yellow, Dragonite in Gold and Silver.

**Comment by DiabloStorm** [comment]
Have I got good news for you.

![image](https://user-images.githubusercontent.com/63818362/212499331-a74f8cbf-9998-403b-8756-3a7831c67d06.png)

**Comment by jojobear13** [comment]
I want to keep the Lite branch vanilla when it comes to movepools since it's more for people to do their own thing. 

Charizard can learn fly in the master branch already. 

But Dragonite...ah yes...this has tugged at me as well. I don't want to just up and give it Fly. Maybe I'll make it into a secret. I do so miss when games had secrets.

**Comment by jojobear13** [comment]
Added in commit 4bfcb88fe7d4a71f9730ade6c2949f04dc76f7ee
