### ISSUE TITLE
Adjust AI's unfair advantage during switches.

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#252]
A few things I suspect: The order of operations is completely wrong in this romhack (i.e. AI is able to choose their move AFTER you switch; **this is not how the game has ever worked for the player**, you claim AI switching is a new feature of this hack so maybe it's implemented wrong for AI, they should be forced to use whatever move they selected and apply it to the newly switched pokemon, this isn't what's happening) **or** the AI has been granted the ability to change move selection(i.e. AI selects move, you switch, they choose to use a different move instead of their original choice) **OR** the cpu knows a switch is going to happen and what is being switched into, **or** some combination of the 3.)

_Originally posted by @DiabloStorm in https://github.com/jojobear13/shinpokered/issues/234#issuecomment-1370366498_

Player switches: AI seemingly begins turn after the switch completes. They're able to choose super effective moves against the switching-in pokemon and certainly will if they have them.

AI switches: Player has little to no idea the AI has chosen to switch, the move the player previously selected fires against the newly switched-in pokemon, player does not get the same option the AI gets to choose a better move.

**Comment by DiabloStorm** [comment]
No idea how to add labels after the fact.

**Comment by DiabloStorm** [comment]
If this comes down to that "50% blind to player switching" it shouldn't.

It's an issue with the order of operations. The AI should be forced to select and stick with a move, not able to anticipate a switch at all because that takes place AFTER they've already selected their move. Then the player switches and the AI should be forced to fire the move they selected.

**Comment by jojobear13** [comment]
Allow me to clarify. The switching AI, being the decision-making scoring system on when/if/what to switch, is what is new. 

The ability for the AI to switch at all is in the vanilla game. Specifically, jugglers switch 50% of the time, and Agatha randomly switches on rare occasions. It is also not well-implemented, with AI only being able to switch back and forth between their active pokemon and the next pokemon in their roster. Furthermore, the AI performs their switch after the player uses a move. 

The vanilla battle engine is hard-coded so that the enemy makes move selections right after a player selects a move. These "selection" procedures have a lot of other things that they do (like checking for recharge or wrap status and what not), so they cannot be moved around without rewriting a large number of battle effects. The annoying part is that player switches and items are executed *before* the enemy selects a move. Player switching and item-use happens during the menu-selecting process, and then the enemy selects its move once the battle menu goes away. As a result, the enemy move selection occurs based on the instantaneous state right after the player executes his actions. 

Try this for fun: In vanilla red/blue/yellow, use a move to put a status on one of Brock's pokemon. He will instantly use a Full Heal out of order and in perfect response to your actions. https://v.redd.it/ca3sagllpkk71

I might be able to make it so that the SwitchPlayerMon function is called *after* the enemy selects its move. But this will take a bit of doing. No guarantees.

**Comment by DiabloStorm** [comment]
> the AI performs their switch after the player uses a move.

yup.



> Try this for fun: In vanilla red/blue/yellow, use a move to put a status on one of Brock's pokemon. He will instantly use a Full Heal out of order and in perfect response to your actions.

yup. This and the Lance issue you mentioned probably should be reworked. Reason? Not fun. Make "fun" the reason if nothing else.


> I might be able to make it so that the SwitchPlayerMon function is called _after_ the enemy selects its move. But this will take a bit of doing. No guarantees.

better than nothing. anything to tone down the current predictive way the AI functions.

**Comment by jojobear13** [comment]
In the meantime, until a better solution can be discovered, commit 6620fccf0dc01a447713fd612ed7f9d657895e3b heavily nerfs the omniscience of AI layer 3 (type-matching evaluation for moves).

If the player has switched, each individual move the AI evaluates has a ~90% chance to skip having knowledge of the sent-out mon's typing. This change to Layer 3 will cause it to bias things towards STAB moves and moves that complement its own stats in the event that the player switches. Example: switching Venusaur into an opposing Starmie will cause the Starmie to not immediately punish with Ice Beam. Instead, it will more likely pick a decent attacking move at random with a preference for something like Surf.
