### ISSUE TITLE
Compatibility error with Yellow

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#254]
![bgb00006](https://user-images.githubusercontent.com/63818362/214793241-c8bee160-8ddc-4a41-9b61-d891ee1cb5f1.gif)
![bgb00007](https://user-images.githubusercontent.com/63818362/214793249-f40ca245-f0fe-48d4-aa74-41f0bc909ba9.gif)
![bgb00008](https://user-images.githubusercontent.com/63818362/214793263-f30c0a66-4f2e-4b7b-b358-f779923e7ed2.gif)

FYI name was not Originally GEY.

Traded with yellow, it even changed the OT and ID. Seems like a major bug. First noticed it when I tried to walk around and was out of usable pokemon. Yellow's game doesn't recover after blacking out. Can't use potion on it either, this essentially borks the entire save file. (unless i can manage to trade back, luckily i'm on the square i need to be standing on)

Here is the pikachu received. 
![bgb00006 (2)](https://user-images.githubusercontent.com/63818362/214794456-ddb60582-2dae-4c4a-8ecc-1761bb9aedec.gif)
Name deleted from default "PIKACHU"
![bgb00007 (2)](https://user-images.githubusercontent.com/63818362/214794588-597bbb32-5305-4668-984f-05456646cdc7.gif)
OT completely missing, ID intact tho.

This is retail Yellow Pikachu <-> Shin Red Pidgey

Anyway, good luck with this one, maybe it's because yellow's pikachu has special data attached that nobody here anticipated, but I wouldn't know. If you want to reproduce, I traded a sacrificial level 3 pidgey for yellow's pikachu at the earliest point you can trade in yellow.

**Comment by jojobear13** [comment]
[test.zip](https://github.com/jojobear13/shinpokered/files/10515335/test.zip)

**Comment by jojobear13** [comment]
I just ran an experiment with my latest local build and didn't run into any issues. Here is a video (zipped and 7zipped due to github's file restrictions) that shows what I did.
[2023-01-26 18-12-11.zip](https://github.com/jojobear13/shinpokered/files/10515338/2023-01-26.18-12-11.zip)

Here is the test folder with the files I used in case you want to try and replicate the video.
[test.zip](https://github.com/jojobear13/shinpokered/files/10515339/test.zip)

To me, it almost looks a little like packet loss. Like data is being dropped mid-communication. The pidgey didn't transfer the first three characters of its name, so the receiving game loads data in the wrong place and then asks for three more bytes worth of garbage data to fill the whole request. 

It's also possible this might be a bug with BGB's link functionality. I don't really know of an emulator that does it perfectly because most game boy games that use the link cable had zero data integrity checks.

**Comment by DiabloStorm** [comment]
Yeah, BGB is a possibility

**Comment by DiabloStorm** [comment]
I'll attempt this again with my backup saves in a bit.

**Comment by DiabloStorm** [comment]
This was likely BGB.

Selecting Listen + Connect on both BGB windows reproduces error.

Selecting Listen on one and Connect on the other trades normally.
