### ISSUE TITLE
Inquiry about reduction of vitamin limitation after E4

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#257]
So, I was prepping Petit Cup and Pika Cup teams for stadium, and realized that within this hack one could easily have a cheated amount of stat exp due to this change. Thoughts? (Yes dragon rage absolutely obliterates in stadium, but the point is, I had to measure "doses" and the original imposed limitations to not be actively cheating in stadium) This somehow feels not very "true" or intended.

Maybe restrict mist stone and the "higher vitamin limit" to pokemon above level 30. (incidentally coincides with my playthrough where you'd have to be about level 30 minimum anyway to have max stat exp, feasibly, but I say above level 30 because when you're at level 30 that's the highest level for Petit Cup affected by this)

In a similar vein, I don't necessarily like the expanded (originally illegal) movepools enabled after stone evolutions in this hack. When I was leveling my staryu, I had to put thought into which path I was going to take, tradeback from gen 2 for parafusion, or stay in gen 1 and give up confuse ray? Taking confuse ray sacrifices ~~a lot of available moves~~ two very relevant moves. This hack denies you of putting any thought like this into it, just gives you every move whether it's illegal or not, I just find that kind of lame. In starmie's case I consider it straight up cheating ~~without the use of breeding which requires quite a few more steps than say, fly on dragonite which is as simple as transferring to gen 2 and teaching it the HM and transferring back.~~ On second thought, genderless pokemon actually cannot pass down level-up moves at all. So yes, this is blatant cheating. (if a starmie has confuse ray and lightscreen/hydro pump)

**Comment by jojobear13** [comment]
Good suggestion on the vitamins. Never thought of the Petite Cup.

By illegal moves on the stone evos, I assume you mean what's possible taking the Gen 2 time capsule into account. The "trade-back meta" with Gen-2 was not taken into account for this project due to scope (preferring to preserve the 1997 move pools). Might revisit this later in a future patch.

**Comment by jojobear13** [comment]
Level 30 is actually a pretty good cutoff by my calculations. Consider this:

One of the best statEXP-to-lvlEXP ratio mons for grinding with the intent of boosting stat exp while gaining as few levels as possible is nidoran-f. You can grind level 2 nidoran-f in blue or green version on route 22 right at the start of the game, and each one you KO gets you 13 exp and an average of 47 statEXP per stat. Due to how the stat formulas work their rounding, statEXP values stop having an affect at about 64000 points (no need to max at 65535).

This means you can max out your stat exp in nearly all stats on a pokemon right at the beginning of the game by grinding 1,362 nidoran-f of level 2. This will net you 17,706 level exp. This means the highest legal level for max statEXP is 28 for fast-growth mons and 24 for slow-growth mons.

**Comment by DiabloStorm** [comment]
Sounds about right. I didn't know about the 64000 thing though. Are you sure nidoF gives 13 exp?

my ghetto discord notes:
![image](https://user-images.githubusercontent.com/63818362/216888658-862b31dd-6b77-46b9-978b-afcdc82d8a78.png)

**Comment by jojobear13** [comment]
Looks like I rounded wrong. Still, EVs are going to cap out between lvl 30 and lvl 25

**Comment by jojobear13** [comment]
I think I understand the illegal moveset via time capsule  a bit better.

The main issue seems to be where a stone evolution has a "unique" move that is learned and after which the move list either stops or deviates. It creates a branching path in the learnable moves.

Right now I've identified starmie, cloyster, poliwrath, and exeggcutor as affected by this.

Basic rule I've identified for maintaining 1997 moveset compatibility as well as "time capsule meta" legality is thus. All moves learned by a stone evolution after the level the moveset branches off mush either:
- Follow the new branch
- Be a gen-1 learnable TM
- Be a gen-1 level 0 default move

So in the case of starmie, hydro pump and light screen are illegal after level 37. But bubblebeam and reflect, being TMs, would be fine.

**Comment by DiabloStorm** [comment]
I appreciate you looking into this. days ago I was holding my typing fingers because I honestly think it's a mistake to discount gen 2 tradeback meta, as all of the games are kind of tied together by design, love it or hate it.

**Comment by DiabloStorm** [comment]
> So in the case of starmie, hydro pump and light screen are illegal after level 37. But bubblebeam and reflect, being TMs, would be fine.

Yes, but keep in mind Staryu/Starmie only ever learns reflect via TM, it's lightscreen that's a part of it's level-up move list.

**Comment by jojobear13** [comment]
>I guess Starmie is unique? It can't learn confuse ray any other way, the other ones you've mentioned can easily use a TM or they learn a duplicate of a move they already learn in RBY just at a different level?

Right. Starmie seems to be a special case in gen-2. It's learning a move (confuse ray) that was completely unavailable to it in Gen 1. Contrast this with something like Exeggutor which learns stomp in Gen 2 at level 19 instead of level 28 and then also adds in Egg Bomb (a gen-1 tm it can access).

**Comment by jojobear13** [comment]
Movesets adjusted in commit 7044f2de62d25e5a9c283556ba87528b3e96919e

Vitamin limitation added in commit 36881cf078bc71e211398a2206daeb8109ed1659
