### ISSUE TITLE
Koffing (and other derpy sprites) question

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#258]
Feel free to correct, but I believe it was "fixed" in gen 1? Maybe a JP version?

Why was the one with an error retained for red/blue?

Similarly (this is arguably opinion based) most of these sprites are amazing (back sprites) but there are still a number of original derpy front sprites used. Was this due to a lack of official good looking ones? Or if this project isn't limiting itself to that...a lack of sprite replacements in general?

In my opinion these original sprites are some of the derpiest remaining ones:
An old relic from the fat sprite days
![bgb00008 (2)](https://user-images.githubusercontent.com/63818362/216483563-0249997b-01c4-418a-a514-ccd4e7c131ff.gif)
giant foreboding egg in the back lol
![bgb00010](https://user-images.githubusercontent.com/63818362/216483570-c9c54ead-0fd9-4fa1-a93c-2e9f220b6365.gif)
mirrored left and right sides even more apparent than what they did with krabby
![bgb00009](https://user-images.githubusercontent.com/63818362/216483577-c57526da-f905-4ffa-a4e3-f3ab8f5b00de.gif)
face and marking swap error special for us westerners
![bgb00011](https://user-images.githubusercontent.com/63818362/216483608-249fb0f7-c36c-4868-88dd-804e33c975d9.gif)

**Comment by jojobear13** [comment]
Koffing's Blue sprite was never fixed in gen 1. That's just how it is. All the sprites for gen 1 (and I believe gen 2) were created from scratch, and then Sugimori did all the official watercolor art based off those (though some would continue to get tweaked, like in Bellossom's case).

This hack isn't super intent on sprite replacements baked-into the patches. Instead, the front sprites are those that match the proper version of the game. The spaceworld back sprites were added because it's so painfully obvious they were meant to be paired with the Blue front sprites, but for what ever reason they never made it in. Even still, I have "original backs" patches because some people get really picky anytime the graphics change.

I did add a bunch of compiler tags and reorganized how sprites are stored in ROM so that it's very easy to compile any rom with any sprite set. I would love to have all the fronts and backs be swap-able in-game, but that's going to be a bigger project than I have time for at the moment.

**Comment by DiabloStorm** [comment]
> Koffing's Blue sprite was never fixed in gen 1.

https://www.serebii.net/pokearth/sprites/green/109.png

Is this not koffing's pokemon green sprite? Which came out before blue/red?

**Comment by jojobear13** [comment]
Correct. The green sprite came first, so it's not really a "fix" to the blue sprite. With the blue sprites, they started playing around with more dynamic perspectives. For koffing, it looks like they wanted it to face down-left towards the player pokemon but had to compromise in order to show its crossbones mark. Chalk it up to artistic experimentation, some of it better than others.
