### ISSUE TITLE
Bug: Instant text speed prevents TX_SFX from playing

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#259]
**What emulator and/or hardware are you are using?**
Lemuroid for Android

**What version of this project are you using?**
v1.23M built from source commit https://github.com/jojobear13/shinpokered/commit/cc28c3da068a883bdfe37406eb6251d467cc40e9

**What is the problem you encountered?**
When there's a text sound effect embedded in a string, it does not play if the text speed is set to instant; you only hear the text advance sound.

**Expected behavior**
TX_SFX should be allowed to play fully before allowing the player to advance text.

**Is it possible to reproduce the problem?**
Easy to see with Bill when he gives the SS Ticket - `TX_SFX_KEY_ITEM` should play as part of `SSTicketReceivedText` but does not.

**Comment by jojobear13** [comment]
Known issue. Has to do with the fact that it is just a re-activation of the "0-frame text speed" bug from vanilla. Since this bug is so widely used by speedrunners and has been shown to be stable for many years, it was option-ized instead of being properly fixed and/or eliminated.

Currently unknown why this causes text sfx to not play.

**Comment by jojobear13** [comment]
fixed in commit 6b4ac8f784f4d7b958845d36dd9609f6b7802870

**Comment by Mord5** [comment]
I checked it out and it seems like the fix works for the TX_SFX. Other SFX called differently are still obscured by the text-advance sfx. One that I noticed prominently was `SFX_SHRINK` during `OakSpeech`. Looks like tossing a `call WaitForSoundToFinish` on the line before https://github.com/jojobear13/shinpokered/blob/47cef1f8e3d478d93d0cd5282b57901c93bd1721/engine/oak_speech.asm#L197 fixes it but idk if this is the best solution.

**Comment by jojobear13** [comment]
Let's keep this one open. I might have an idea to attack the problem at the source.

**Comment by jojobear13** [comment]
Okay, let's give this solution in commit 8b4b647fda60b9c4b9b4e2f8e4a3154d5e89b064 a try. Here is how it works.

The main problem is that the TINK sfx from text boxes is still loaded and prevents new sfx from playing. Normally this is not a problem when there is a text delay because the TINK finishes before the next sfx needs to play. But when there is zero text delay, there is not enough time for the TINK to finish and unload from the sfx channels.

What I did was go into PrintLetterDelay and make it so that, if zero delay text is active, it checks to see if anything is loaded in the sfx channels. If so, it sets a flag to indicate that a sfx has played while printing text.

The next step is to go into the PlaySound function and check & reset that flag. If that flag was set, then you know you are trying to play a new sfx right after one that played during text-printing. Make a call to WaitForSoundToFinish to make sure the previous sfx has completely unloaded from the sfx channels before continuing with the next sound.

That should hopefully cover every scenario.
