### ISSUE TITLE
Bug: Trainers facing down have view capped to 3 tiles

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#273]
**What emulator and/or hardware are you are using?**
bgb 1.5.9.w64

**What version of this project are you using?**
built from source master_dev commit https://github.com/jojobear13/shinpokered/commit/43b63b6f6eb93674af1580741b3686096a868e10

**What is the problem you encountered?**
Any trainer with a defined view range of 4 cells that faces downwards actually only has a view range of 3 cells. Can be seen with the southernmost Biker on Route 14:
<img width="478" alt="image" src="https://github.com/jojobear13/shinpokered/assets/52078365/4fe24fd8-9fbc-4a51-a944-27feb9bab663">
```
Route14TrainerHeader6:
	dbEventFlagBit EVENT_BEAT_ROUTE_14_TRAINER_6
	db ($4 << 4) ; trainer's view range
	dwEventFlagAddress EVENT_BEAT_ROUTE_14_TRAINER_6
	dw Route14BattleText7 ; TextBeforeBattle
	dw Route14AfterBattleText7 ; TextAfterBattle
	dw Route14EndBattleText7 ; TextEndBattle
	dw Route14EndBattleText7 ; TextEndBattle
```

**Comment by jojobear13** [comment]
Verified that this is a Gamefreak original.

![image](https://github.com/jojobear13/shinpokered/assets/47074297/a3f21441-05b8-462e-904e-75117c05e9c5)

**Comment by jojobear13** [comment]
I tracked down the cause. There is a bug in TrainerEngage.linedUpX, let me explain.

Sprites are offset by 4 pixels towards the top of the screen for perspective.

Top of the player's hat is always Y=$3C pixels from the top of the screen.

Vertical distance is always calculated between the top of the player's head and the top of the NPC's head.

When the NPC is 4 spaces above the player, the top of its head is off of the screen. The top of the screen is Y=0, so this means the top of the NPC's head underflows by 4 pixels to Y=$FC.

This results in the distance being calculated wrong: $3C - $FC = $C0 instead of the expected $40.

<img width="201" alt="capture 1" src="https://github.com/jojobear13/shinpokered/assets/47074297/ad8baac0-56a9-4497-9c06-
<img width="236" alt="capture 2" src="https://github.com/jojobear13/shinpokered/assets/47074297/3ad5afc0-82ed-43ec-8ab7-4c04a9f3e7cf">
aed7caad947a">
