### ISSUE TITLE
Position of Boulders in Victory Road

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#29]
Wouldn't it be more realistic to place the boulders on the switch after the switch has been activated? It doesn't make any sense to reset them to their initial position when re-entering the cave while the switch remains active.

Update: This is not so simple. First I tried to add a missable boulder on top of the switch to reveal after the event. However, this has two drawbacks: 1) We need to update data stored in the SAV which will result in an unstable game in an ongoing playthrough, 2) The hidden boulder actually collides with the one we want to push on the switch (even if is indeed invisible).
The only other way that I can think of in order to do this would be to update the boulder's position each time we enter the map along with the updated tile.

**Comment by jojobear13** [comment]
Right. Missable objects don't just dissappear. They still exist and have collision rules. Hiding them just stops them from being drawn and let's the player walk through them. 

New missable objects don't make for unstable saves. The data bits are all there from the start and initialized, so adding a new missable object is just a matter of assigning an existing resource to it. But it can cause a weird effect. Unused missable object bits are initialized to "show" at the start of a new game. Adding a new object in a save file will cause it to default to "show", and you'll need default it to "hide" via script.

You are on the right track though. Best way to do this might be to check the victory road boulder-on-switch events in the map scripts and then change the coordinates of the boulders accordingly.

**Comment by wisp92** [comment]
Right the bits are initialized. However, due to the way constants/hide_show_constants.asm and data/hide_show_data.asm are structured, we need to add the missable constant in between the other values. Wouldn't this shift all the bits and messing with which bit corresponds to each value?

As for the coordinates, I am not sure how to track the boulder's address offset yet. I need to understand a bit more of that.

**Comment by jojobear13** [comment]
> Right the bits are initialized. However, due to the way constants/hide_show_constants.asm and data/hide_show_data.asm are structured, we need to add the missable constant in between the other values. Wouldn't this shift all the bits and messing with which bit corresponds to each value?

Only the pointers in MapHSPointers needs to be in the order of map constants. Adding a new map just means you erase the corresponding MapHSXX and in its position put in a new MapHS## function for the map. That can technically go anywhere in the byte-list below the pointer function.

The trick is the hide/show constant list. The predef function for hide/show uses that as a pointer list to the byte-list previously mentioned. So adding a new missable object in the bytelist requires you to define a constant for it in the same position in the constant list. 

The good news is the constant list is just for the compiler. As long as you don't go changing the names of the constants around the compiler will handle the list being bigger or smaller. You would just need to change all the comments because obviously those would be shifted.

**Comment by wisp92** [comment]
Thank you very much for your detailed explanation. So, if it wasn't for the collision problem we could fix these using two missable constants (I'll note this for the future). However, in this case, we must relly on moving the boulder. So I'll try to figure that out first.

**Comment by jojobear13** [comment]
Keep in mind a few things about how the Victory Road switches and their associated event flags reset.

The 1F switch resets in two instances: A) you enter the 2F map. B) you enter the Indigo Plateau lobby. The first prevents the player from just running back out if things get too tough; an escape rope or field move has to be used in order to wimp out. The second seems to be an oversight or a last-second fix by Gamefreak, and it should be placed in the route 23 map script. 

The 2F and 3F boulders reset on route 23 as one would expect. You have to go through route 23 to get into victory road, so the player is forced to go through these switch puzzles on every entry and there is no way to go backwards through it. It is the final dungeon before the boss gauntlet after all.

So in terms of moving the boulders into position via script, the 1F boulder can be ignored since going off the 1F map needs to reset the associated event anyway.

**Comment by wisp92** [comment]
Yes, I noticed that and I was thinking of fixing the oversight with a bugfix and, additionally, to propose a tweak where the boulders stay in place after activation.

Although I like the tweak I don't want to alter the game more than necessary, especially in the Lite version. After I finish it I'll propose it for the master version and you can decide if you like it.

**Comment by wisp92** [comment]
Update: After reading the code a bit more I think the second theory is probably the correct one. In Victory Road 2 the reset code is meant to be executed if bit 6 of wCurrentMapScriptFlags is set. No, pret team speculated that this is a multipurpose flag used in various instances. Specifically, bit 6 is set at the end of a battle in home.asm. The only reason I can imagine of to reset a flag, in this case, is a basic debugging method back in that era.

**Comment by jojobear13** [comment]
Pull slated for playtesting. Will get to it sometime this weekend.
