### ISSUE TITLE
Bug: Typos in Green version

### ISSUE THREAD

**Issue by PokefanMarcel** [jojobear13/shinpokered#339]
Reporting a few typos I noticed during my playthrough of ShinGreen:

Pokedex:
- Lickitung: like *an* arm
- Paras: wrong opening quotation mark (should be `, not ')
- Alakazam: *at will* (no dash)
- Rhyhorn: extra period at the end
- Lapras: extra period at the end
- Dodrio: *embodied*
- Oddish: opening quotation mark
- Poliwrath: extra period at the end
- Electrode: opening quotation mark
- Seaking: extra period at the end
- Haunter: in *the* dark
- Hitmonchan: missing period at the end of first sentence

Oak dialogue is missing a period:
- your Pokédex is entirely complete*.* Congratulations!

Orange champion dialogue:
- *Seiga* should be capitalized as SEIGA to be consistent with all other names in the game

**Comment by jojobear13** [comment]
Corrections Made:

-     Lickitung: like an arm
-     Alakazam: at will (no dash)
-     Rhyhorn: extra period at the end
-     Lapras: extra period at the end
-     Poliwrath: extra period at the end
-     Seaking: extra period at the end
-     Hitmonchan: missing period at the end of first sentence

Non-Straightforward Corrections:
-     Paras: wrong opening quotation mark (should be `, not ')
-     Oddish: opening quotation mark
-     Electrode: opening quotation mark
--> Apostrophes were used because the text tileset does not have a quotation mark. Will change to uppercase to denote proper nouns and nicknames like the rest of the game.
-     Dodrio: embodied
-     Haunter: in the dark
--> Running up against character limit for lines. Used a thesaurus for some words to shorten length.

**Comment by jojobear13** [comment]
fixed in commit 9642a9578

**Comment by jojobear13** [comment]
Good ideas all around. I did forget a few things.

I looked into the Oak dex rating. There already is an exclamation mark, but there is an issue with line length. Each line can have a max of 18 characters including spaces. EXCEPT for the last line before a line scroll because the flashing cursor takes up the 18th space. As you can see below, the cursor overwrites the exclamation point. 

Not enough space to hyphenate "entirely" upwards to the top line. I'm open to ideas here.

![image](https://github.com/jojobear13/shinpokered/assets/47074297/d195699f-d7b7-42cb-93af-56cf774a4404)

**Comment by PokefanMarcel** [comment]
I don't see a good answer either, it's tricky! I would personally prefer to remain conservative in this case, and leave the small typo rather than changing the original translation...

Although if change there must be I guess 'fully' would be the better option.

**Comment by jojobear13** [comment]
I think I found a good solution. I discovered an unused text-function character that auto-scrolls the line without a button press or printing the flashing cursor. All I had to do was add in a 30-frame delay so that the first line is legible before it goes away.

![ezgif-3-35113a2810](https://github.com/jojobear13/shinpokered/assets/47074297/89c94bfc-a11e-4519-86aa-8f1062e76a3f)

**Comment by PokefanMarcel** [comment]
Very elegant solution! It looks great.
