### ISSUE TITLE
Bug: Mega Drain misses against Substitute

### ISSUE THREAD

**Issue by CostaCostaCosta** [jojobear13/shinpokered#349]
**Review the [Compatibility Notes](https://github.com/jojobear13/shinpokered/#compatibility-notes)**
In particular, not all emulators or non-official hardware solutions are supported due to bugs induced from lack of accuracy. Proper bugs should be able to be replicated on official hardware or, to a lesser extent, the latest version of the BGB emulator.

**What emulator and/or hardware are you are using?**
Delta iOS
**Which patch are you using?**
v1.24.6M red

**What ROM base are you using?**
red US

**How are you utilizing the patch?**
Please list any tools/accessories that are used to utilize the patch with your owned ROM copy (patching programs, retroarch, 3rd-party reproduction hardware, etc). Please provide a version number if possible.

**What version of this project are you using?**
v1.24.6M

**What is the problem you encountered?**
Mega Drain is missing every time against substitute. This is likely due to the code change for sub blocking status moves. There are no accuracy or evasion modifier

**Expected behavior**
Mega Drain is a damaging move and should hit the substitute

**Is it possible to reproduce the problem?**
If so, please list the exact steps taken to reproduce the erroneous behavior.
Example:
2. Talk to '....'
3. Press '....'

**Screenshots/Video**
If applicable, attach screenshots or video you've taken to help explain your problem.

**SAV file or Save States**
Attaching your raw .sav file and/or a BGB save state file is also helpful (but not required).

**Additional context**
Great job with this romhack. Thank you for your efforts

**Comment by jojobear13** [comment]
[See the readme under "move fixes":](https://github.com/jojobear13/shinpokered/blob/ad676ad2361c4b8945ead701bc956cfc4ced1e77/README.md?plain=1#L578)  
``` 
- Substitute-related fixes:
    - all hp drain moves (including dream eater and leech seed) miss against substitute
    - substitute will not work if it would bring you to exactly 0 hp
    - zero power moves that inflict stat-downs, sleep, or paralyze will not affect a substitute
    - the confusion side-effect of damaging moves is blocked by a substitute
    - recoil damage from jump kicks or hurting oneself in confusion is now applied to user's substitute
```

Mega Drain and other HP-draining moves are not supposed to hit a substitute doll in Generation 1. This was a bug introduced only into the western localizations of the Game Boy games. This bug does not exist in the Japanese releases. It was fixed in all versions of Stadium and in all Generation 2 games.


Quote Bulbapedia's entry on Substitute:

> In Generations I and II (except the localized Generation I handheld games), [HP-draining moves](https://bulbapedia.bulbagarden.net/wiki/Category:HP-draining_moves) always fail if the target is behind a substitute.

Quote Bulbapedia's entry on Mega Drain:

>In the Japanese version of [Generation I](https://bulbapedia.bulbagarden.net/wiki/Generation_I) games, and all versions of the [Pokémon Stadium series](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Stadium_series) and [Generation II](https://bulbapedia.bulbagarden.net/wiki/Generation_II) games, Mega Drain will always miss if the target has a substitute.

The bug itself [exists in the function MoveHitTest](https://github.com/jojobear13/shinpokered/blob/ad676ad2361c4b8945ead701bc956cfc4ced1e77/engine/battle/core.asm#L6235) where calling CheckTargetSubstitute erases the move effect value held in the A register. The localizer forgot to reload the effect value from the pointer address in DE back into A, so the checks for dream eater and other draining effects would never trigger. The localizer also totally forgot to account for the Leech Seed effect.

HP-draining moves would gradually be allowed to hit substitute dolls over the course of generations 3 through 5.

>From Generation III onward, HP-draining moves except [Dream Eater](https://bulbapedia.bulbagarden.net/wiki/Dream_Eater_(move)) can successfully hit substitutes and drain HP from them. In Generation III and IV, Dream Eater fails if the target has a substitute; starting in Generation V, Dream Eater can also successfully hit a substitute (as long as the Pokémon behind it is asleep).
