### ISSUE TITLE
New How To Guide for Adding New Maps to the Game

### ISSUE THREAD

**Issue by mattcit** [jojobear13/shinpokered#73]
I created an MD file that explains how to add new maps into the game, specifically what all .asm files need edited to add a new map into the game. Let me know if you want me to send it (I'm new to Github so I'm not sure of the correct ways to contribute).

**Comment by jojobear13** [comment]
You need to learn how to do commits and pull/merge in github. Proper way to do this is to create a fresh branch that is consistent with the master_dev branch. Then you need to create a commit for it that does nothing but add that MD guide to the "how to guides" folder. Then, using that commit, create a pull request in order to merge that file into the shinpokered/master_dev branch. Merging tries to smoosh all the differences together, so you don't want to try this with your main project that has lots of other changes made to it.
