### ISSUE TITLE
update to match pokered?

### ISSUE THREAD

**Issue by MoriyaFaith** [jojobear13/shinpokered#76]
From what I can tell, the disassembly is made from an older version of pokered (seen with the existence of a pic folder). Is there any way to update the repository to more closely match a newer version of pokered?

**Comment by WilliamOfBlobs** [comment]
If I could diff it with the version it's based on, I could probably make the changes to update it to modern pokered then send in a PR after verifying the ROMs match with the current version of Shin.

**Comment by jojobear13** [comment]
Shin split off back in November or December 2018. I'd have to gradually update it manually but I'm not really up to the task right now. One of the issues with git repositories of different projects is that they kinda go off in their own directions. Trying to keep your project concurrent with its parent repository means that eventually someone renames a function or a file which breaks something in your own code. I eventually just settled on a release then went from there rather than constantly be debugging things with every git pull.

**Comment by MoriyaFaith** [comment]
Ok, makes sense.
